# Generated by Django 3.1 on 2020-08-09 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200808_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todomodel',
            name='time',
            field=models.CharField(max_length=250),
        ),
    ]
